import { mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { $, browser, expect } from "@wdio/globals";
import { button, controlByLabel, pinMainWindow, selectOptionByText, waitForBodyText } from "./support";

describe("Agent collaboration through native IPC and a fixture CLI", () => {
  it("creates a mission, runs tasks, answers a question, reads output and releases a worker", async () => {
    if (!process.env.TF_AGENT_FIXTURE_STATE) throw new Error("This journey requires the isolated fixture runner");
    await pinMainWindow();
    await (await button("添加工作区")).click();
    await (await controlByLabel("工作区名称")).setValue("Agent 原生验证");
    await (await controlByLabel("工作区目标")).setValue("验证任务控制链路，不调用模型");
    await (await button("确认创建")).click();
    await waitForBodyText("Agent 原生验证");
    await (await button("Agent 协作")).click();
    await waitForBodyText("1.4.206-fixture");
    const repository = await controlByLabel("代码仓库", "select");
    const option = await repository.$('option[value="fixture-repo"]');
    await selectOptionByText(repository, await option.getText());
    await (await controlByLabel("协作目标", "textarea")).setValue("原生 Agent 协作闭环");
    await (await button("创建协作")).click();
    await waitForBodyText("已连接 · 每 5 秒更新进展");
    await (await controlByLabel("任务标题")).setValue("验证协作任务");
    await (await controlByLabel("任务说明", "textarea")).setValue("仅执行 fixture，不读取或修改项目文件；用固定文本验证输出。");
    await (await button("启动 OMP 任务")).click();
    await waitForBodyText("任务已提交");
    const task = await $('[aria-label="任务 验证协作任务"]');
    await task.waitForDisplayed();
    await (await controlByLabel("任务标题")).setValue("并行验证任务");
    await (await controlByLabel("任务说明", "textarea")).setValue("第二个独立 fixture 任务；不得调用模型或修改代码。");
    await (await button("启动 OMP 任务")).click();
    await (await $('[aria-label="任务 并行验证任务"]')).waitForDisplayed();
    const reply = await $('textarea[aria-label^="回复问题 "]');
    await reply.waitForDisplayed();
    await reply.setValue("确认，继续 fixture 验证");
    await (await button("发送回复")).click();
    await browser.waitUntil(async () => (await task.getText()).includes("已完成") || (await task.getText()).includes("已执行"));
    await (await task.$("details.agent-workspace__output > summary")).click();
    await (await button("读取输出")).click();
    await expect(await task.$(".agent-workspace__output pre")).toHaveText(expect.stringContaining("OMP fixture output; no model was called"));
    mkdirSync(resolve("output"), { recursive: true });
    await task.scrollIntoView();
    await browser.saveScreenshot(resolve("output/agent-workspace-native.png"));
    await (await button("释放已结束的 Agent")).click();
    await waitForBodyText("已释放");
    const remainingReply = await $('textarea[aria-label^="回复问题 "]');
    await remainingReply.waitForDisplayed();
    await remainingReply.setValue("确认第二个任务独立完成");
    await (await button("发送回复")).click();
    const secondTask = await $('[aria-label="任务 并行验证任务"]');
    await browser.waitUntil(async () => (await secondTask.getText()).includes("已完成"));
    await (await button("释放已结束的 Agent")).click();
    await browser.waitUntil(async () => (await secondTask.getText()).includes("已释放"));
    // The WebView is reconstructed; mission identity and operation receipts come from SQLite.
    await browser.refresh();
    await pinMainWindow();
    await (await button("Agent 协作")).click();
    await waitForBodyText("原生 Agent 协作闭环");
    await waitForBodyText("已释放");
    await expect(await $('[aria-label="任务 并行验证任务"]')).toHaveText(expect.stringContaining("已释放"));
    await expect(await $('[aria-label="历史协作"]')).not.toHaveValue("");
  });
});
